# Generated by Django 4.2.7 on 2024-01-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
