# Generated by Django 4.2.7 on 2024-01-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YG', '0005_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback_images/')),
                ('message', models.TextField()),
            ],
        ),
    ]
